### ISSUE TITLE
Is it possible to use my own scenes in this? 

### ISSUE THREAD

**Issue by Jeremy5909** [TheScienceElf/TI-84-CE-Raytracing#3]

**Comment by TheScienceElf** [comment]
Yes, you can find most of the scene configuration in src/scene.h though you will need to build the executable yourself for these changes to take effect. There are currently some limitations on custom scenes though that you should be aware of.

- Planes can only be axis-aligned
- Planes can only exist within a 2x2x2 box around the origin
- You can only have one point light source

Other than that, you should be able to add more spheres, change colors, add textures and whatever else you might want to play with. Have fun!

**Comment by Jeremy5909** [comment]
Im not the brightest so what file type can this use? obj? I want to make a simple scene maybe made with blender
