### ISSUE TITLE
Unable to figure out how to get files onto calculator

### ISSUE THREAD

**Issue by ageekdude** [TheScienceElf/TI-84-CE-Raytracing#4]
After reading through the instructions, I was unable to figure out how to get the files onto my calculator. I downloaded the app, plugged in my calculator, and saw it on the app. However, I don't know where I should put those files and how to run them. Could you provide a bit more of a detailed explanation of how to do that?

**Comment by TheScienceElf** [comment]
You should be able to open the app, click "Calculator Explorer" on the left, select your calculator, and then drag and drop the files you want to load onto your calculator into the window.  

Once the program is on your calculator, use Catalog (on the zero key) to type `Asm(` then use the PRGM key to add `DEMO`

You want to run the command `Asm(prgmDEMO)`

The program shouldn't take longer than 15 minutes to run, (if it does, you'll want to use the RESET button along the back of the calculator) and once it finishes, you should be able to return to the OS by pressing any key.

Again, be warned that if the program freezes and you need to reset, you will lose anything saved in RAM that hasn't been archived.
