### ISSUE TITLE
Program freezes when computing sphere radiosity

### ISSUE THREAD

**Issue by AAM1075** [TheScienceElf/TI-84-CE-Raytracing#5]
I can't compile the program without the program freezing on the step "Computing Sphere Radiosity".
I have also noticed that the file that I compiled is 58 KB, but the one from this repo is 59 KB. What could be the reason for this?

**Comment by mateoconlechuga** [comment]
This has been fixed in #2 (so you can check out that PR if you want to build it) - make sure that you update your toolchain to the latest version, [available here](https://github.com/CE-Programming/toolchain/releases/latest).

**Comment by AAM1075** [comment]
oh wow, I totally forgot I had opened this. Thanks @mateoconlechuga!
